# Generated by Django 4.2.1 on 2023-05-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayman', '0002_service_created_at_service_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='default/testimonial.jpg', upload_to='testimonial'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default/about.jpg', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default/blog.jpg', upload_to='blog'),
        ),
    ]
