# Generated by Django 4.2.1 on 2023-05-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayman', '0003_testimonial_image_alter_about_image_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='freelance',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default=('Available', 'Available'), max_length=50),
        ),
    ]
