# Generated by Django 4.2.1 on 2023-05-29 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ayman', '0004_about_freelance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='birthday',
        ),
        migrations.AddField(
            model_name='about',
            name='profession',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
