# Generated by Django 4.2.1 on 2023-05-29 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ayman', '0006_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='introduction',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
